[package]
name = "raykwon"
version = "0.1.0"
authors = ["Adam Latos <adam.latos@nokia.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
# minifb = "0.16.0"